.github/workflows/run-macro-micro-dummy.yml
examples/macro-micro-dummy/run_micro_manager.py
micro_manager/micro_manager.py

since the micro manager splits the mesh as a cube, we can end up with empty micro manager instances. 
E.g we have cube region but a hexagonal mesh on the other side - with enough cpu's this can result in the micro manager instances on the corners of the cube being empty.
Without this change these empty instances will crash and block the whole simulation.

Allow empty micro manager instances instead of crashing

---

.github/workflows/run-adaptivity-test.yml
.github/workflows/run-macro-micro-dummy.yml
.gitignore
README.md
examples/macro-micro-dummy/micro-manager-config.json
examples/macro-micro-dummy/micro_dummy.py
micro_manager/adaptivity.py
micro_manager/config.py
micro_manager/micro_manager.py
tests/integration/test_adaptivity/clean-test.sh
tests/integration/test_adaptivity/macro_solver.py
tests/integration/test_adaptivity/micro-manager-config.json
tests/integration/test_adaptivity/micro_solver.py
tests/integration/test_adaptivity/precice-config.xml
tests/integration/test_adaptivity/run_micro_manager.py

This PR adds functionality to allow for adaptive control of micro simulations. In each time step, the manager computes a similarity distance between each pair of micro simulations to determine how similar or dissimilar they are. The active and inactive simulations are then updated using this distance. After all the micro simulations are divided into active and inactive ones, each inactive micro simulation is linked to the most similar active one.
The adaptivity concept is taken from two previous works:
- Redeker, Magnus & Eck, Christof. (2013). A fast and accurate adaptive solution strategy for two-scale models with continuous inter-scale dependencies. Journal of Computational Physics. 240. 268-283. 10.1016/j.jcp.2012.12.025. 
- Bastidas, Manuela & Bringedal, Carina & Pop, Iuliu. (2021). …

Add local variant of adaptive control strategy

---

micro_manager/adaptivity.py
micro_manager/micro_manager.py
tests/integration/test_adaptivity/precice-config.xml

When an inactive micro simulation is associated to an active micro simulation, the micro simulation object of the active simulation needs to copied over to the inactive simulation entry. This was not done before. If this is not done, when the inactive simulation is activated again, it will calculate the state from when it was deactivated, which could have been multiple time steps before.

Fix bug in adaptivity association step

---

micro_manager/adaptivity.py
micro_manager/micro_manager.py

This PR sets local and global ID of copied active simulation to the original IDs of the previously inactive simulation. If we do not do this, the newly activated micro simulation will have the same local and global ID as the active simulation which it was copied from.
First stopped via https://github.com/precice/micro-manager/pull/29#issuecomment-1508148493

Resolve bug in copy operation when inactive simulation is activated

---

examples/cpp-dummy/micro_cpp_dummy.cpp
examples/cpp-dummy/micro_cpp_dummy.hpp

This PR adds functionality to allow for pickling and unpickling of the C++ micro simulation code in the C++ solver dummy. This is based on the [pickling support documentation of pybind11](https://pybind11.readthedocs.io/en/latest/advanced/classes.html#pickling-support).

Add pickling support to C++ solver dummy

---

.github/workflows/check-pep8.yml
.github/workflows/run-adaptivity-test.yml
.github/workflows/run-macro-micro-dummy.yml

This PR changes on which branches the tests are being run. When its `"*"` the tests are run twice for each PR. Therefore only testing on each push for `develop` and `main` is preferred.
The changed is discussed in #37

Change branches to run tests on push

---

.github/workflows/update-website.yml

As discussed in https://github.com/precice/precice.github.io/pull/270#issuecomment-1564091378, this PR adds a workflow that updates the preCICE website any time the documentation is updated.
The action is copied from the [openfoam adapter](https://github.com/precice/openfoam-adapter/blob/develop/.github/workflows/update-website.yml)

Add update-website workflow

---

docs/configuration.md
examples/micro-manager-adaptivity-config.json
examples/micro-manager-config.json
micro_manager/config.py
tests/integration/test_unit_cube_dummy/micro-manager-config-adaptivity.json
tests/integration/test_unit_cube_dummy/micro-manager-config-parallel-1.json
tests/integration/test_unit_cube_dummy/micro-manager-config-parallel-2.json
tests/unit/micro-manager-unit-test-adaptivity-config.json
tests/unit/micro-manager-unit-test-config.json

As stated in the title of the PR.

Create sub-heading adaptivity under simulation_params to shorten config variable names

---

.github/workflows/run-macro-micro-dummy.yml
docs/configuration.md
docs/running.md
examples/README.md
micro_manager/config.py

Closes #36
This PR removes `os.path.dirname(sys.argv[0])` as part of the folder path, moving from a absolute to a relative path in the micro-manager configuration.

Move to a relative path configuration

---

examples/README.md
examples/cpp-dummy/micro_cpp_dummy.hpp

Remove deepcopy from solverdummy

---

micro_manager/config.py

Warn if only micro-scale data is used in the similarity computation of adaptivity.

---

micro_manager/adaptivity/global_adaptivity.py
micro_manager/micro_manager.py
tests/unit/test_adaptivity_parallel.py

This PR resolves a bug mentioned in the title. There is also some refactoring done on the side.

Make global adaptivity work for cases where ranks have unequal number of micro simulations

---

docs/micro-simulation-convert-to-library.md
examples/cpp-dummy/micro_cpp_dummy.cpp
examples/cpp-dummy/micro_cpp_dummy.hpp
examples/python-dummy/micro_dummy.py
micro_manager/micro_simulation.py
tests/integration/test_unit_cube/micro_dummy.py
tests/unit/test_micro_manager.py

Uniqueness of micro simulations is critical if the user wants to manipulate the creation in some way, for example, to create a certain number of micro simulations of a particular type. To allow the user to uniquely identify micro simulations, this PR makes the Micro Manager pass the global ID to the user-side MicroSimulation class.

Pass global IDs to micro simulations to make them unique

---

micro_manager/adaptivity/adaptivity.py
micro_manager/adaptivity/global_adaptivity.py
micro_manager/adaptivity/local_adaptivity.py
tests/unit/test_adaptivity_parallel.py

The following bugs are fixed:
- The step of updating inactive simulations did not take the correct states from the previous step of updating active simulations.
- If a situation arises that all the simulations are exactly the same in terms of their output, and all of them are active, the global adaptivity implementation fails to compare them and deactivate all but one simulation. This PR adds functionality to handle this scenario. This can typically happen at the start of a simulation.

Fix bugs in adaptivity computation

---

micro_manager/micro_manager.py

Replace the `allgather` call in initialization, with an `Allgatherv` call.

Handle unequal number of micro simulations on ranks

---

docs/micro-simulation-convert-to-library.md
micro_manager/adaptivity/global_adaptivity.py
micro_manager/micro_manager.py
tests/unit/precice.py
tests/unit/test_adaptivity_parallel.py

The `initialize()` function is reintroduced as an optionally function that the micro simulation library can have. If the function exists, the Micro Manager calls it. The function is expected to return data, otherwise it does not have any purpose from the perspective of the coupling. The data returned from the function is checked for matching names with the data given for adaptivity. If matched, the adaptivity functionality is called based on this data *before* the coupling starts.

Reintroduce initialize function in the micro simulation API

---

micro_manager/micro_manager.py

This removes an unnecessary import of the `MicroSimulation` class that was not used. In a personal meeting, we also discussed if one of the logger level sets could be removed but on further investigation, they seem to serve slightly different purposes.

Remove unused import of micro simulations

---

micro_manager/micro_manager.py
tests/unit/test_micro_manager.py

The [documentation of `__import__()`](https://docs.python.org/3/library/functions.html#import__) states that "Direct use of `__import__()` is [...] discouraged in favor of importlib.import_module()"

Minor improvements: fix typo in test, remove redundant code and replace __import__

---

micro_manager/micro_manager.py

In the step-by-step guide on precice.org it is suggested to get the maximum allowed time step size from preCICE before calling advance.
To me it looks dangerous how things are done at the moment, because actually the following is happening:
```
self._participant.advance(self._dt)
self._dt = self._participant.get_max_time_step_size()
t += self._dt
n += 1
```
We tell preCICE "I just finished window `n` with time step size `self._dt`, but then update the internal time `t` by the step size of the **upcoming** window. I always prefer to first do all the updates and then call advance:
```
self._dt = self._participant.get_max_time_step_size()    # assuming this has been called at the beginning of the current time step
...
t += self._dt 
n += 1
self._participant.advance(self._dt)  # tell preCICE: …
```

TBD: Follow time stepping proposed in documentation

---

.github/workflows/run-unit-tests.yml
examples/python-dummy/micro_dummy.py
micro_manager/interpolation.py
micro_manager/micro_manager.py
setup.py
tests/unit/micro-manager-config_crash.json
tests/unit/test_interpolation.py
tests/unit/test_micro_manager.py
tests/unit/test_micro_simulation_crash_handling.py

This is an attempt to solve issue #74.
This cannot be a permanent solution to the handling of crashing simulation. If a simulation crashes during the first time step, it is replaced with data from another random simulation. In the long run, I don't see any other solution than an interpolation (in cases where only one simulation is given and it cannot be replaced by one of different complexity).
Moreover, it has not been tested with real simulations, in parallel, or using spack.

Handle crashing micro simulations

---

micro_manager/micro_manager.py

This PR adds functionality to use initial data written by the macro side for initializing the micro simulations. This is done only when the `initialize()` function in the micro simulation library requires the macro data as input. The requirements of data are checked rigorously to catch possible mismatches.

Optionally use initial macro data to initialize micro simulations

---

CHANGELOG.md
docs/micro-simulation-convert-to-library.md
micro_manager/micro_manager.py

Title is self-explanatory.
Checklist:

Check if initial data returned from the micro simulation is the data that the adaptivity computation requires

---

CHANGELOG.md
micro_manager/micro_manager.py

Handle the case where micro simulations written in C++ have the `initialize()` function

---

CHANGELOG.md
micro_manager/__init__.py
micro_manager/__main__.py
micro_manager/micro_manager.py
micro_manager/micro_manager_base.py
pyproject.toml
tests/unit/test_micro_manager.py
tests/unit/test_micro_simulation_crash_handling.py

In preparation for the Snapshot computation #101 this PR adds base classes to reduce code repetitions. This introduces a new interface class `MicroManagerInterface`, a base class `MicroManager` and renames the original `MicroManager` class in `MicroManagerCoupling`. The PR also changes the structure and position of the `main`-method to allow snapshot execution via a flag as suggested in #101. 
This is also done with the idea to extend this base class in a potential future restructuting process of the `MicroManagerCoupling` class. 
Feedback on how to implement the base classes in clean way is highly apprecitated  as I wasn't able to find examples or best practices regarding this scenario, in which a base class handles part of a constrcutor. 
Checklist:

Add base class for Micro Manager and restructure main

---

CHANGELOG.md
docs/configuration.md
examples/micro-manager-cpp-adaptivity-config.json
examples/micro-manager-cpp-config.json
examples/micro-manager-python-adaptivity-config.json
examples/micro-manager-python-config.json
micro_manager/config.py
micro_manager/micro_manager.py
micro_manager/micro_manager_base.py
tests/integration/test_unit_cube/micro-manager-config-global-adaptivity-parallel.json
tests/integration/test_unit_cube/micro-manager-config-global-adaptivity.json
tests/integration/test_unit_cube/micro-manager-config-local-adaptivity.json
tests/integration/test_unit_cube/micro-manager-config-parallel-1.json
tests/integration/test_unit_cube/micro-manager-config-parallel-2.json
tests/unit/micro-manager-config.json
tests/unit/micro-manager-config_crash.json
tests/unit/test_micro_manager.py
tests/unit/test_micro_simulation_crash_handling.py

This PR implements changes which allow for the user to set the initial time window size (dt) of the micro simulation during configuration. The time window size is then using in the coupling, which allows for subcycling. 
**Note**: The micro simulation cannot modify the time window size during the coupling. A followup feature can change the micro simulation library API in a way that the `solve(...)` function call can return the desired time step value of the micro simulation.
Checklist:

Set initial time window size of the micro simulation in the configuration

---

CHANGELOG.md
examples/micro-manager-cpp-adaptivity-config.json
examples/micro-manager-cpp-config.json
examples/micro-manager-python-adaptivity-config.json
examples/micro-manager-python-config.json
micro_manager/config.py
tests/integration/test_unit_cube/micro-manager-config-global-adaptivity-parallel.json
tests/integration/test_unit_cube/micro-manager-config-global-adaptivity.json
tests/integration/test_unit_cube/micro-manager-config-local-adaptivity.json
tests/integration/test_unit_cube/micro-manager-config-parallel-1.json
tests/integration/test_unit_cube/micro-manager-config-parallel-2.json
tests/unit/micro-manager-config.json
tests/unit/micro-manager-config_crash.json

The variable to set the micro simulation dt should be a simulation parameter rather than a coupling parameter. This PR changes the configuration and also all configuration files in the examples and tests. This change also needs to be done for the two-scale-heat-conduction tutorial.
Checklist:

Move micro_dt from coupling parameters to simulation parameters in the configuration

---

CHANGELOG.md
micro_manager/micro_manager.py

Currently, the Micro Manager understands that a time window has converged when the API call `requires_reading_checkpoint()` is false. However, `requires_reading_checkpoint()` may return false when the time window has not converged. This could happen, for example, when the Micro Manager is subcycling. To avoid falsely indicating convergence in the Micro Manager, an explicit check using the API command `is_time_window_complete()` is necessary.
Checklist:

Explicitly check if the time window has completed

---

CHANGELOG.md
micro_manager/micro_manager.py

Put computation of counting active steps inside the adaptivity variant condition

---

micro_manager/adaptivity/global_adaptivity.py
micro_manager/micro_manager.py

This PR adds type hints to variables wherever possible, mainly with static type checking hints from Mypy.
Checklist:

Add static type hints (with prompts from Mypy)

---

CHANGELOG.md
micro_manager/adaptivity/adaptivity.py
micro_manager/adaptivity/global_adaptivity.py
micro_manager/adaptivity/local_adaptivity.py
micro_manager/micro_manager.py
tests/unit/test_adaptivity_parallel.py
tests/unit/test_micro_simulation_crash_handling.py

This PR refactors code related to handling of adaptivity data. The primary intention is to make the implementation cleaner and easier to understand. A second purpose is to remove `if` conditions from the solve routines, to aid performance. The motivation for this refactoring also stems from https://github.com/precice/micro-manager/pull/133 and how logging adaptivity metrics would be easier with the refactored state.
Checklist:

Refactoring adaptivity data handling

---

CHANGELOG.md
micro_manager/adaptivity/adaptivity.py
micro_manager/adaptivity/global_adaptivity.py
micro_manager/adaptivity/local_adaptivity.py
micro_manager/micro_manager.py
tests/unit/test_adaptivity_parallel.py
tests/unit/test_adaptivity_serial.py
tests/unit/test_micro_simulation_crash_handling.py

This PR reduces copying and handover of large data structures between the adaptivity classes (`LocalAdaptivityCalculator` and `GlobalAdaptivityCalculator`) and the `MicroManagerCoupling` class. This is done to make the Micro Manager operations cheaper for large simulations.
Checklist:

Reduce data handovers between adaptivity classes and the MicroManagerCoupling class

---

CHANGELOG.md
micro_manager/adaptivity/adaptivity.py
micro_manager/config.py
micro_manager/micro_manager.py
micro_manager/tools/logging_wrapper.py
tests/integration/test_unit_cube/micro-manager-config-global-adaptivity-parallel.json
tests/unit/test_adaptivity_parallel.py
tests/unit/test_adaptivity_serial.py

As mentioned in the title.
Checklist:

Set default logger to stdout and add output directory setting option for file loggers

---

CHANGELOG.md
docs/configuration.md
examples/micro-manager-cpp-adaptivity-config.json
examples/micro-manager-cpp-config.json
examples/micro-manager-python-adaptivity-config.json
examples/micro-manager-python-config.json
micro_manager/config.py
micro_manager/micro_manager.py
micro_manager/snapshot/dataset.py
tests/integration/test_unit_cube/micro-manager-config-global-adaptivity-parallel.json
tests/integration/test_unit_cube/micro-manager-config-global-adaptivity.json
tests/integration/test_unit_cube/micro-manager-config-local-adaptivity.json
tests/integration/test_unit_cube/micro-manager-config-parallel-1.json
tests/integration/test_unit_cube/micro-manager-config-parallel-2.json
tests/unit/micro-manager-config.json
tests/unit/micro-manager-config_crash.json
tests/unit/snapshot-config.json
tests/unit/test_micro_manager.py
tests/unit/test_snapshot_computation.py

The `scalar` and `vector` keyword values for data name dictionaries are no longer necessary as the preCICE v3.x API does not distinguish between the data dimensions it works with. No functionality in the Micro Manager relies on this user information.
Checklist:

Remove the scalar and vector keywords from data names in configuration

---

.github/workflows/run-adaptivity-tests-parallel.yml
.github/workflows/run-adaptivity-tests-serial.yml
CHANGELOG.md
micro_manager/adaptivity/adaptivity.py
micro_manager/micro_manager.py

The Micro Manager could not handle the case where a micro simulation returns vector data in the form of a list. This was because the data collection for adaptivity was done on a predefined `numpy.array` data structure. Now the data collection is done in a Python list and the list is converted to a NumPy array only just before the data is used for the similarity calculation.
Checklist:

Fix bug in handling of vector data

---

.github/workflows/run-adaptivity-tests-parallel.yml
.github/workflows/run-adaptivity-tests-serial.yml
.github/workflows/run-domain-decomposition-tests.yml
CHANGELOG.md
micro_manager/micro_manager.py
tests/integration/test_unit_cube/clean-test.sh
tests/integration/test_unit_cube/micro-manager-config-global-adaptivity-parallel.json
tests/integration/test_unit_cube/micro-manager-config-global-adaptivity.json
tests/integration/test_unit_cube/micro-manager-config-load-balancing.json
tests/integration/test_unit_cube/micro-manager-config-local-adaptivity.json
tests/integration/test_unit_cube/micro-manager-config-parallel-1.json
tests/integration/test_unit_cube/micro-manager-config-parallel-2.json
tests/integration/test_unit_cube/micro_dummy.py
tests/integration/test_unit_cube/precice-config.xml
tests/integration/test_unit_cube/unit_cube.py

Adaptivity can be computed either once in a time window, or once in every time iteration. For explicit coupling scenarios, these two cases are one and the same. The current logic did not reflect this and hence adaptivity was incorrectly computed for explicit coupling scenarios. This PR fixes the problem.
Checklist:

Fix adaptivity calling for explicit coupling

---

CHANGELOG.md
micro_manager/domain_decomposition.py
micro_manager/micro_manager.py
tests/unit/test_domain_decomposition.py

The domain decomposition was yielding incorrect results for cases which have the same number of domains in the `x` and `y` directions, for example `[2, 2, 1]`. This PR simplifies the algorithm and adds tests to ensure that the potentially problematic scenario is covered for.
Checklist:

Simplify the algorithm for domain decomposition

---

CHANGELOG.md
docs/configuration.md
examples/precice-config-adaptivity.xml
micro_manager/adaptivity/global_adaptivity.py
micro_manager/adaptivity/local_adaptivity.py
micro_manager/config.py
micro_manager/micro_manager.py
tests/integration/test_unit_cube/precice-config.xml

This change is made because the adaptivity computation CPU time is not a micro simulation specific data, but just one single global data (for global adaptivity). For local adaptivity, the CPU time is unique for every rank, and it is probably a good idea to aggregate the data and output it. The CPU time is now calculated by default, and written to the `adaptivity-metrics.csv` file instead of being exported using the preCICE export functionality.
Checklist:

Move adaptivity CPU time output from preCICE export to metrics logging

---

CHANGELOG.md
micro_manager/adaptivity/global_adaptivity.py
micro_manager/adaptivity/local_adaptivity.py
micro_manager/micro_manager.py
tests/unit/test_micro_manager.py
tests/unit/test_micro_simulation_crash_handling.py

The export of adaptivity computation CPU time is no longer relevant because a newer implementation has been done in https://github.com/precice/micro-manager/pull/141 which uses the preCICE profiling API.
Checklist:

Remove export of adaptivity CPU time

---

CHANGELOG.md
micro_manager/micro_manager.py

If a simulation is created lazily, that is after the adaptivity computation is done, it needs to be checkpointed, only if preCICE requires writing a checkpoint. Right now a checkpoint is always stored, which is incorrect.
Checklist:

Checkpoint lazily created simulation only if a checkpoint is necessary

---

CHANGELOG.md
docs/configuration.md
docs/logging.md
micro_manager/adaptivity/adaptivity.py
micro_manager/adaptivity/global_adaptivity.py
micro_manager/adaptivity/local_adaptivity.py
micro_manager/micro_manager.py

The function `log_metrics` causes a deadlock at the moment, due to an incorrect implementation of a MPI Gather command. This PR fixes and also improves the metric logging. Bug reported by @steffenger
Checklist:

Fix adaptivity metrics logging and add logging documentation

---

CHANGELOG.md
micro_manager/adaptivity/adaptivity.py
micro_manager/adaptivity/global_adaptivity.py
micro_manager/adaptivity/local_adaptivity.py

If a simulation is deactivated and then tagged for activation in the same time window, it does not have an associated active simulation to get the state from. The association is also not necessary, because the current state can simply be carried forward. This PR handles this case in the global and local adaptivity.
Checklist:

Handle adaptivity case when deactivation and activation happens in the same time window

---

CHANGELOG.md
micro_manager/adaptivity/adaptivity.py

When the data of all the micro simulations used for adaptivity is the same, the similarity distance matrix has zeros. Such a situation should lead to exactly one active simulation, with all the rest inactive. The starting value of the minimum distance in the association step needs to be greater than zero to ensure the correct adaptivity states.
Checklist:

Trigger adaptivity when all the adaptivity data is the same

---

CHANGELOG.md
docs/configuration.md
micro_manager/adaptivity/adaptivity.py
micro_manager/adaptivity/global_adaptivity.py
micro_manager/adaptivity/local_adaptivity.py
micro_manager/config.py
micro_manager/micro_manager.py

This PR ...
- ... adds a configuration option `adaptivity_output_type`, which can either be `local`, `global`, or `all`.
- ... changes the existing configuration option `output_memory_usage` is also now to be set to either `local`, `global`, or `all`.
- ... adds the configuration option `memory_usage_output_n` to be set to control the output frequency of the peak memory usage.
**Breaking change**: The existing configuration option `output_dir` is renamed to `output_directory` for consistency.
Checklist:

Add config options for adaptivity metrics and memory usage output to allow for different levels

---

micro_manager/adaptivity/adaptivity.py
micro_manager/adaptivity/local_adaptivity.py
micro_manager/micro_manager.py

The subprocess command for the creation of the output directory is moved from the adaptivity base class to the main `MicroManagerCoupling` class, because the directory needs to be created for simulations without adaptivity too.

Move creation of output directory into main coupling class

---

CHANGELOG.md
micro_manager/adaptivity/adaptivity.py
micro_manager/adaptivity/global_adaptivity.py
micro_manager/adaptivity/local_adaptivity.py
tests/unit/test_adaptivity_parallel.py
tests/unit/test_adaptivity_serial.py

In the adaptivity computation, the similarity distance matrix is the most memory heavy data structure. Currently it is stored on every rank, which leads to a memory bottleneck for large problems. This PR implements sharing of the similarity distance matrix between ranks on a compute node. This will lead to a memory benefit of as many times as the number of ranks per node. Shared access is implemented using MPI, by following the strategy from [this example](https://groups.google.com/g/mpi4py/c/Fme1n9niNwQ/m/lk3VJ54WAQAJ).
Checklist:

Share similarity distance matrix between ranks on a compute node
